// Generated by CoffeeScript 1.6.3
(function() {
  window.Proto = {
    alias: function(elems, opts) {
      if (opts == null) {
        opts = {};
      }
      _.defaults(opts, {
        scope: document,
        "static": false
      });
      _.each(elems, function(item, key) {
        var val;
        if (opts["static"]) {
          val = jQuery(opts.scope).find(item);
          return elems[key] = function() {
            return val;
          };
        } else {
          return elems[key] = function() {
            return jQuery(opts.scope).find(item);
          };
        }
      });
      return elems;
    },
    staticAlias: function(elems, opts) {
      if (opts == null) {
        opts = {};
      }
      _.defaults(opts, {
        "static": true
      });
      return Proto.alias(elems, opts);
    },
    pluckClass: function(elem, classes, timeout) {
      elem().toggleClass(classes);
      return Proto.after(timeout, function() {
        return elem().toggleClass(classes);
      });
    }
  };

}).call(this);
