// Generated by CoffeeScript 1.6.3
(function() {
  var animation, elems, stat;

  elems = Proto.alias({
    btn: 'button.main',
    listItems: '.somelist li'
  });

  stat = Proto.staticAlias({
    btn: 'button.main',
    listItems: '.somelist li'
  }, {
    scope: 'div.scoped'
  });

  $('body, .scoped').append($('<button class="main">New button</div>'));

  elems.btn().css({
    color: 'red'
  });

  stat.btn().css({
    'background-color': '#eee'
  });

  Proto.pluckClass(listItems, 'animationName', 3000);

  Proto.pluckProperty(listItems, {
    opacity: 1
  }, 2000);

  animation = Proto.timeline({
    '0s': function() {
      return doSomeStuff();
    },
    '2s': function() {
      doSomeOtherStuff();
      if (typeof error !== "undefined" && error !== null) {
        return animation.stop();
      }
    },
    '4s': function() {
      return doEvenDifferentStuff();
    },
    options: {
      autostart: false,
      repeat: 'infinite'
    }
  });

  animation.start();

  animation.pause();

  animation.resume();

  Proto.after('2s', function() {
    return doStuff();
  });

  Proto.commitAnimations();

}).call(this);
